FROM python:3-slim


ENV PYTHONUNBUFFERED 1

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./requirements.txt /requirements.txt
RUN pip install --proxy=http://10.10.10.7:80 -r /requirements.txt

RUN mkdir /app
WORKDIR /app
COPY main.py /app

# RUN adduser -D user
# USER user
CMD ["python", "main.py"]